### ISSUE TITLE
Typo in code sample

### ISSUE THREAD

**Issue by Hazzeldorn** [breadbutter/breadbutter-js#2]
https://github.com/breadbutter/breadbutter-js/blob/53f21d105555b3559334eeba34ff07735be09e9c/README.md?plain=1#L233

Hi guys

The de-identification code example in the README.md does not work because of a typo. It should be `BreadButter.widgets.deIdentification()` (with a capital i).

Cheers,
Hazzeldorn

**Comment by isiah-bb** [comment]
Corrected in latest version.
